server:
  port: 8080

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/truck_db?useSSL=false&allowPublicKeyRetrieval=true&createDatabaseIfNotExist=true
    username: root
    password: Sayis.
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
  jackson:
    time-zone: America/Bogota

# logging:
#  level:
#    root: INFO
